2020-01-30 20:50:52,359 - F:/PythonWork/pythonLearn/logutils.py[line:38] - DEBUG: debug
2020-01-30 20:50:52,359 - F:/PythonWork/pythonLearn/logutils.py[line:39] - INFO: info
2020-01-30 20:50:52,359 - F:/PythonWork/pythonLearn/logutils.py[line:40] - WARNING: 警告
2020-01-30 20:50:52,359 - F:/PythonWork/pythonLearn/logutils.py[line:41] - ERROR: 报错
2020-01-30 20:50:52,360 - F:/PythonWork/pythonLearn/logutils.py[line:42] - CRITICAL: 严重
2020-01-30 20:51:34,130 - F:/PythonWork/pythonLearn/logutils.py[line:38] - DEBUG: debug
2020-01-30 20:51:34,131 - F:/PythonWork/pythonLearn/logutils.py[line:39] - INFO: info
2020-01-30 20:51:34,131 - F:/PythonWork/pythonLearn/logutils.py[line:40] - WARNING: 警告
2020-01-30 20:51:34,131 - F:/PythonWork/pythonLearn/logutils.py[line:41] - ERROR: 报错
2020-01-30 20:51:34,131 - F:/PythonWork/pythonLearn/logutils.py[line:42] - CRITICAL: 严重
2020-01-30 21:02:35,973 - F:/PythonWork/pythonLearn/logutils.py[line:38] - DEBUG: debug
2020-01-30 21:02:35,974 - F:/PythonWork/pythonLearn/logutils.py[line:39] - INFO: info
2020-01-30 21:02:35,974 - F:/PythonWork/pythonLearn/logutils.py[line:40] - WARNING: 警告
2020-01-30 21:02:35,974 - F:/PythonWork/pythonLearn/logutils.py[line:41] - ERROR: 报错
2020-01-30 21:02:35,974 - F:/PythonWork/pythonLearn/logutils.py[line:42] - CRITICAL: 严重
2020-01-30 21:04:51,101 - F:/PythonWork/pythonLearn/logutils.py[line:38] - DEBUG: debug
2020-01-30 21:04:52,322 - F:/PythonWork/pythonLearn/logutils.py[line:39] - INFO: info
2020-01-30 21:04:55,319 - F:/PythonWork/pythonLearn/logutils.py[line:40] - WARNING: 警告
2020-01-30 21:04:56,495 - F:/PythonWork/pythonLearn/logutils.py[line:41] - ERROR: 报错
2020-01-30 21:04:57,064 - F:/PythonWork/pythonLearn/logutils.py[line:42] - CRITICAL: 严重
